name: CI (pull-requests-only jobs)

on:
  pull_request:
    branches:
      - master

jobs:
  buildsh:
    env:
        DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer
    strategy:
      matrix:
        mode: [cocoapods-lint-default-subspecs, cocoapods-lint-other-subspecs]
        include:
          - mode: cocoapods-lint-default-subspecs
            name: Verify that default subspecs lint
          - mode: cocoapods-lint-other-subspecs
            name: Verify that other subspecs lint
    name: ${{ matrix.name }}
    runs-on: macos-latest
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v2
    - name: Run build script
      run: ./build.sh ${{ matrix.mode }}

  SPM:
    name: Build from SPM manifest
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.1.1.app/Contents/Developer
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,name=iPhone 12 Pro", "platform=macOS,variant=Mac Catalyst", "platform=tvOS Simulator,name=Apple TV 4k"]
        scheme: ["AsyncDisplayKit", "AsyncDisplayKitIGListKit"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Starting from Xcode 11 `xcodebuild` supports SwiftPM packages out of the box
      # to test that we have  valid swift package we need to remove existing *.xcodeproj/xcworkspace
      # `xcodebuild` will invoke Package.swift. 
      - name: spm's xcodebuild - ${{ matrix.destination }}
        run: |
          set -o pipefail
          rm -rf AsyncDisplayKit.xcodeproj/
          rm -rf AsyncDisplayKit.xcworkspace/
          xcodebuild clean build -scheme "${{ matrix.scheme }}" -destination "${{ matrix.destination }}"

